### ISSUE TITLE
Class Input not defined

### ISSUE THREAD

**Issue by nuxsmin** [splitbrain/dokuwiki-plugin-swiftmail#12]
Hi, I'm having an error when I try to access to the plugin configuration page:

```Fatal error:  Call to a member function bool() on a non-object in /var/lib/dokuwiki/lib/plugins/swiftmail/admin.php on line 26```

Looking at the code, in "main.php" it uses a class named "Input" that is not implemented in 2012-01-25 "Angua" version (Debian 7 default).

Do you know about it?, is there any solution besides upgrade?.

I can modify the code to remove that class usage, but I think it's not a clean solution.

Kind regards.

**Comment by splitbrain** [comment]
Your DokuWiki needs an upgrade
