### ISSUE TITLE
Does not work with Rincewind?

### ISSUE THREAD

**Issue by wrzasa** [splitbrain/dokuwiki-plugin-swiftmail#24]
Hi, 

I just installed the plugin manually, because it failed to install with plugin manager despite of correct permissions. Plugin is located in `lib/plugins/swiftmail` with apache having read permissions to all files and it seems it is not loaded. It shows neither in the plugin managed nor in settings. I see no error messages on pages and nothing at all in apache error.log. Where can I look for any clues? There's no info about plugin requirements, are there any specific? Anything I can do to debug this problem?

**Comment by splitbrain** [comment]
Rincewind is ancient. Upgrade your wiki.

**Comment by wrzasa** [comment]
Are sure this will help? Is there a specification of requirements where I can check what do I really need to make it work?

**Comment by splitbrain** [comment]
no I'm not sure it will work. but it makes no sense to even start debugging on an outdated dokuwiki

**Comment by wrzasa** [comment]
Thanks for quick answer.
