### ISSUE TITLE
A bug found

### ISSUE THREAD

**Issue by lockpick** [splitbrain/dokuwiki-plugin-swiftmail#29]
i filled a address in configure on a right way.
and, an error occurred followed by :
There was an unexpected problem with sending the email: The sender parameter must either be a valid string email address or an instance of Swift_Address.

at line 95 in "action.php"

                     // skip empty ones
                    if(empty($addr)) continue;
                    // add
                    if($hdr == 'from'){
                        $from =& new Swift_Address($addr,$text);

when  $hdr is equal to 'form', the value of $addr is empty.
because of continue sentence, new Swift_address($addr,$text) is never executed.
$form has a null value when $swift->send() is called.

              $ok = $swift->send($message, $reci, $from);

and, unexpected problem occurred.

I removed 3 lines 

                   if($hdr == 'from'){

,

                    }else{

and

                    }

and, it works.

**Comment by splitbrain** [comment]
can you please send a proper pull request?

**Comment by lockpick** [comment]
i didn't set "mail_from". it's my fault.
