### ISSUE TITLE
Mail not sent

### ISSUE THREAD

**Issue by borpin** [splitbrain/dokuwiki-plugin-swiftmail#3]
I am getting this error

There was a problem communicating with SMTP: The SMTP connection failed to start [tls://borpin.co.uk:25]: fsockopen returned Error Number 0 and Error String ''

the settings I am using work fine for WordPress.

How do I get a more full log?

**Comment by steji113** [comment]
Hello, this seems to still be an issue, supposedly with version 3.3.2 of switfmail, as noted here: http://forge.prestashop.com/browse/PSCFV-10102

Any way to upgrade to the latest swiftmail version for doku wiki?
